In [13]:
from quantecon import DiscreteRV
import numpy as np
import scipy as sp
psi = 0.1, 0.9
d = DiscreteRV(psi)
d.draw(5)

array([1, 1, 1, 1, 1])

In [7]:
type(d)

quantecon.discrete_rv.DiscreteRV

In [10]:
isinstance(d, DiscreteRV)

True

In [12]:
isinstance(5, int)

True

In [59]:
P = np.random.rand(3, 4)

In [63]:
P

array([[ 0.07110084,  0.29289783,  0.78163512,  0.09272462],
       [ 0.96225541,  0.9272179 ,  0.50003269,  0.39267102],
       [ 0.18979068,  0.25307909,  0.24892473,  0.76951829]])

In [72]:
len(P)

2

In [70]:
def ts(P, init, sample_size):
    if isinstance(init, tuple):
        X0 = DiscreteRV(init).draw(1)
    elif isinstance(init, int):
        X0 = init
    else:
        raise ValueError
    X = np.empty(sample_size)
    for i in range(1, sample_size):
        X[i] = DiscreteRV(P[X[i-1], ]).draw(1)
    return X

In [71]:
from quantecon import mc_sample_path
P = np.array([[.4, .6], [.2, .8]])
s = mc_sample_path(P, init=(0.5, 0.5), sample_size=100000)
print((s == 0).mean())  # Should be about 0.25

s2 = ts(P, init=(0.5, 0.5), sample_size=100000)
print((s2 == 0).mean())

0.24947
0.24882


In [74]:
from quantecon import mc_compute_stationary
P = np.array([[.4, .6], [.2, .8]])
print(mc_compute_stationary(P))

[[ 0.25  0.75]]
